version: "3"

services:
  fdk-dataservice-harvester:
    build: .
    environment:
      - RABBIT_USERNAME=admin
      - RABBIT_PASSWORD=admin
    ports:
      - "8081:8080"
    depends_on:
      - fdk-fuseki-service
      - rabbitmq

  fdk-fuseki-service:
    image: eu.gcr.io/digdir-fdk-infra/fdk-fuseki-service:staging_latest
    volumes:
      - /etc/fuseki/databases/
    ports:
      - "3030:8080"

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
