openapi: 3.0.2
info:
  title: FDK dataservice harvester
  description: Harvests dataservices in DCAT-AP-NO v2, for use in fellesdatakatalog
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://digdir.no'
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: dataservices
    description: Harvested dataservices
paths:
  /catalogs:
    get:
      tags:
        - dataservices
      summary: Get all harvested catalogs
      operationId: getCatalogs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Catalog"
  /catalogs/{id}:
    get:
      tags:
        - dataservices
      summary: Get a specific catalog
      operationId: getCatalog
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Catalog"
        '404':
          description: Not Found
  /dataservices/{id}:
    get:
      tags:
        - dataservices
      summary: Get a specific dataservice
      operationId: getDataservice
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataservice"
        '404':
          description: Not Found
components:
  schemas:
    Catalog:
      properties:
        id:
          type: string
        publisherUrl:
          type: string
          format: uri
        title:
          type: string
        description:
          type: string
        dataservices:
          type: array
          items:
            $ref: '#/components/schemas/Dataservice'
    Dataservice:
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        endpointUrl:
          type: string
          format: uri
        endpointdescription:
          type: string
          format: uri
        contactpoint:
          $ref: '#/components/schemas/Contact'
    Contact:
      properties:
        name:
          type: string