openapi: 3.0.2
info:
  title: FDK dataservice harvester
  description: Tilgjengeliggjør dataservice-beskrivelser fra en dataservice-katalog ihht DCAT-AP-NO v2.0
  version: '1.0'
  contact:
    name: Digitaliseringsdirektoratet
    url: 'https://fellesdatakatalog.digdir.no'
    email: fellesdatakatalog@digdir.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: dcat-ap-no-catalogs
    description: DCAT-AP-NO catalogs
  - name: dcat-ap-no-dataservices
    description: DCAT-AP-NO dataservices
servers:
  - url: 'https://dataservices.fellesdatakatalog.digdir.no/'
    description: Produksjonsmiljø
paths:
  /catalogs:
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returnerer samlinger av kataloger
      operationId: getCatalogs
      parameters:
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
  /catalogs/{id}:
    get:
      tags:
        - dcat-ap-no-catalogs
      description: Returnerer en katalog
      operationId: getCatalogById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: DataService catalog with requested id does not exist
  /dataservices/{id}:
    get:
      tags:
        - dcat-ap-no-dataservices
      description: Returnerer en dataservice
      operationId: getDataServiceById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: catalogrecords
          in: query
          description: Include FDK catalog records
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: OK
          content:
            text/turtle:
              schema:
                type: string
            text/n3:
              schema:
                type: string
            application/rdf+json:
              schema:
                type: string
            application/ld+json:
              schema:
                type: string
            application/rdf+xml:
              schema:
                type: string
            application/n-triples:
              schema:
                type: string
        '404':
          description: DataService with requested id does not exist
  '/update/meta':
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - update
      description: Updates stored turtle files with current meta data
      operationId: updateMetaData
      responses:
        '204':
          description: No Content

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: [ ]
