spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    template:
      routing-key: 'harvester.UpdateSearchTrigger'
      exchange: 'updates'
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  apiRootUrl: http://fdk-nginx-search:8080/api
  # harvest every sixth hour, 10 minutes after apicatalogs update
  harvestCron: 0 10 */6 * * *
  apiRegistrationsFile: ${API_REGISTRATIONS_FILENAME:apis.csv}
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
management:
  endpoints.web.exposure.include: health, readiness

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      routing-key: 'harvester.UpdateSearchTrigger'
      exchange: 'updates'
application:
  apiRootUrl: http://localhost:8080/api
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8103

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: test
application:
  apiRootUrl: ${WIREMOCK_TEST_HOST}/api
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES}
  clusterName: ${FDK_ES_CLUSTERNAME}
server:
  port: 8080
