logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  fusekiUri: ${dcatServiceUri:http://localhost:3030/fuseki/}
  dataserviceEndpoint: dataservice

---
spring:
  profiles: contract-test
