logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  fusekiUri: ${DATASERVICE_FUSEKI_URI:http://localhost:3030/fuseki/dataservice}

---
spring:
  profiles: contract-test
