spring:
  jackson:
    default-property-inclusion: non_null
    date-format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
application:
  apiRootUrl: http://fdk-nginx-search:8080/api
  # harvest every sixth hour, 10 minutes after apicatalogs update
  harvestCron: 0 10 */6 * * *
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}
management:
  endpoints.web.exposure.include: health, readiness

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  apiRootUrl: http://localhost:8080/api
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8103

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: test
application:
  apiRootUrl: ${WIREMOCK_TEST_HOST}/api
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES}
  clusterName: ${FDK_ES_CLUSTERNAME}
server:
  port: 8080
