logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  dataserviceUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataservice
  catalogUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataservice-catalog
application:
  dataserviceUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/dataservices
  catalogUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/catalogs
  harvestAdminRootUrl: ${HARVEST_ADMIN_ROOT_URL:http://fdk-harvest-admin:8080/api}
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}

---
spring:
  profiles: develop
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
fuseki:
  dataserviceUri: http://localhost:3030/fuseki/dataservice
  catalogUri: http://localhost:3030/fuseki/dataservice-catalog
application:
  dataserviceUri: https://dataservice-harvester.staging.fellesdatakatalog.digdir.no/dataservices
  catalogUri: https://dataservice-harvester.staging.fellesdatakatalog.digdir.no/catalogs
  harvestAdminRootUrl: http://localhost:8135/api

---
spring:
  profiles: contract-test
