logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  dataserviceUri: ${DATASERVICE_FUSEKI_URI:http://localhost:3030/fuseki/dataservice}
  catalogUri: ${DATASERVICE_FUSEKI_URI:http://localhost:3030/fuseki/dataservice-catalog}
application:
  dataserviceUri: ${DATASERVICE_HARVESTER_EXTERNAL_URI:http://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/dataservices
  catalogUri: ${DATASERVICE_HARVESTER_EXTERNAL_URI:http://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/catalogs

---
spring:
  profiles: contract-test
