spring.data.elasticsearch:
  repositories.enabled: true
  cluster-nodes: ${FDK_ES_CLUSTERNODES:localhost:9300}
  cluster-name: ${FDK_ES_CLUSTERNAME:elasticsearch}
logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080

---
spring:
  profiles: contract-test
