logging:
  level.root: WARN
  level.no: ${LOG_LEVEL:DEBUG}
  level.org.springframework: WARN
  level.org.springframework.web: WARN
server:
  port: 8080
fuseki:
  dataserviceUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataservice
  catalogUri: ${FDK_FUSEKI_SERVICE_URI:http://fdk-fuseki-service:8080/fuseki}/dataservice-catalog
application:
  dataserviceUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/dataservices
  catalogUri: ${FDK_DATASERVICE_HARVESTER_URI:https://dataservice-harvester.staging.fellesdatakatalog.digdir.no}/catalogs

---
spring:
  profiles: contract-test
